### ISSUE TITLE
Any examples?

### ISSUE THREAD

**Issue by trueadm** [localvoid/kivi#1]
@localvoid Good work on making a performant vdom :)

Any chance you could add the API doc + some examples? If you can get a working TodoMVC application, that would be amazing (I'll build some more benchmarks on it).

**Comment by localvoid** [comment]
@trueadm thanks :)

There is a good chance that I'll implement TodoMVC, probably next week :) I just don't have much time to work on this project right now.

**Comment by steelbrain** [comment]
+1
