### ISSUE TITLE
Plans for coverage report?

### ISSUE THREAD

**Issue by ghost** [localvoid/kivi#3]
Hi dude! Plans for coverage report to show to the world how much of your code is covered by your tests? Word have been awsome!! Like Istanbul or something?

**Comment by localvoid** [comment]
The world should use React :)

There are no coverage reports because this library doesn't have 100% coverage :) And I am not planning to write useless tests that doesn't test anything properly and just increase this coverage numbers, like almost everyone else is doing.

I understand that it is a useful marketing tool, maybe in the future when I stop breaking API, I'll add coverage report with 100% coverage :)

**Comment by jonnyOwnTheWorld** [comment]
Cool dude :) Cool!! I tried your code. Awsome stuff! And I tried to see if I could modify it so I could write tests with sinon and on server? Seems like something like this is realy fuckked up ?? `@types/sinon` and jassi doesn't work for server tests? Jasmine, the pretty old lady you know :+1:  

Cool stuff bro! I'm focusing on your component stuff now.  One more joint and I'm ready to develop some crazy stuff with your awsome code!! Cheers!! Love yea bro!

**Comment by localvoid** [comment]
I just took the first testing library in google search results that had typescript types :)

This library won't be able to work on server without browser, I understand that there are so much hype around universal js right now, but I still haven't seen any example of universal js application with UX that isn't broken. It supports mounting on top of existing html, but it will require writing two different pieces of code that will render on client and server.

**Comment by Kflash** [comment]
@localvoid I was reading this issue, and looked at your workflow. Rollup + Gulp causes tons of issues. Known and uknown. The author have been bugged for 6 months to come up with v2 and still not released. Your pre-bundle to es6 wih Gulp before launching Karma is an overkill :)  

You can look here for a almost identical workflow without Gulp. https://github.com/Kflash/sikky
Mocha is used there. No old lady :) Easy to swap.

I copied your Travis setting and modified it :)

Anyway! Awsome code stuff you have made :) Keep up the good work mate!

**Comment by localvoid** [comment]
@Kflash

>Your pre-bundle to es6 wih Gulp before launching Karma is an overkill :) I saw you are using the rollup TS plugin here.

Yes, agree :)

>Mocha is used there. No old lady :) Easy to swap.

I was actually thinking about switching to https://github.com/substack/tape

**Comment by Kflash** [comment]
@localvoid Sorry for long delayed answer! For future reference. If you need a small TypeScript workflow you may have a look at this one: https://github.com/Kflash/rachelle
