### ISSUE TITLE
Question about features in dah awsome code!

### ISSUE THREAD

**Issue by ghost** [localvoid/kivi#4]
Hey dude! I played around with your AWSWOME code now :-) And was wondering!
Update. Are you ever ever checking if the root node is different, and replace it? Cool stuff bro, so I will explain so you can understand. !!!! Yeah!

Say you create a SPAN element. And want to update to a DIV element.
SPAN and DIV is different, so shouldn't be an update, he bro? Are they replaced at root level? Couldn't see this kind of code.

And what if you got a HUGE tree where the root element are way to different, are the whole tree thrown away and replaced? Or only the root and the existing tree that doesn't need update / replacement moved back again on root element with the DIV?

YEAH! Confusing, right?

Simple then! If DIV and SPAN are different. Are they replaced?

Again! Damn cool stuff bro! It is!

Thunks I was reading about too. Have you included it?

Also Snabbdom have some hook for "normal" elements, not components. Any plans to integrate it? Say I create a DIV element with a SPAN child, and I want to trigger transition animation that need a create and update hook?

Cheers! Keep up the good work! Love yeah!

**Comment by localvoid** [comment]
>Are you ever ever checking if the root node is different, and replace it?

No, API doesn't provide any way to specify different tag for the root node. Haven't seen any use case when it is necessary.

>And what if you got a HUGE tree where the root element are way to different, are the whole tree thrown away and replaced? Or only the root and the existing tree that doesn't need update / replacement moved back again on root element with the DIV?

All vdom libraries will replace entire tree if tag doesn't match.

>Thunks I was reading about too. Have you included it?

Components cover way much more use cases than thunks.

>Also Snabbdom have some hook for "normal" elements, not components. Any plans to integrate it? Say I create a DIV element with a SPAN child, and I want to trigger transition animation that need a create and update hook?

Container Managers should solve use cases with transitions:

https://github.com/localvoid/kivi/blob/master/lib/container_manager.ts
https://github.com/localvoid/kivi/blob/master/lib/vnode.ts#L529

With this API it will be easy to create reusable ContainerManagers, just store CM in component state and assign to VNode container. But I am not using CMs in any projects, so there is a high chance that there will be bugs :)

**Comment by localvoid** [comment]
>Container Managers should solve use cases with transitions

After thinking about this problem, I've decided to completely remove Container Managers https://github.com/localvoid/kivi/commit/ebb5d65d6b44f00adedfff9dbdddebef1c6badc8
And I was thinking about this problem for a long time :) I had similar hooks in one of my earliest vdom implementations even before snabbdom existed.

Use case with transitions can be solved in a similar way React implements transition containers, I don't think anymore that hooks is the right way to do it.

**Comment by jonnyOwnTheWorld** [comment]
Hi dude! Sorry but I had a rough weekend with the bottles :( yeah! I figured something was wrong after I dl  your latest code.  My code broke!! So yeah you removed cm? And no hooks dude? I'm not familiar with react. Would be awsome if you could kick my assignment in the right direction here. React sucks inot my world dude. 

How you would do it?  What's so nasty with hooks? I thought they was helpfull?  React has some life cycle crazy stuff going on. Isn't that a hook? 

Sorry bro!  My brain is fucked up.  Love yeah and your awsome code! !

**Comment by localvoid** [comment]
>How you would do it?

Implement it as a Component that will perform its own simple diff algo before rendering virtual nodes:
https://github.com/facebook/react/blob/master/src/addons/transitions/ReactTransitionGroup.js

>React has some life cycle crazy stuff going on. Isn't that a hook?

Yes, Component life cycle hooks are important. I was talking about hooks that change the behavior of children reconciliation algorithm, they can cause serious problems in some cases like delaying appearance of a node, I thought that it will be easy to solve it by using comment nodes as a placeholders, but it is actually way more complicated. And when I've tried to cover all edge cases, the code just became significantly more complex, I don't think that it is worth to overcomplicate the code because of this use cases, especially if it can be solved in a much more elegant way by diffing data in Component before creating virtual nodes.
